### ISSUE TITLE
Phonetic_Exclusions.txt does not belong to package 

### ISSUE THREAD

**Issue by shkarupa-alex** [nsu-ai/russian_g2p#21] opened 2018-06-29 04:57 UTC
"data" directory does not copies into target directory during installation

>>> from russian_g2p.Grapheme2Phoneme import Grapheme2Phoneme
>>> your_transcriptor = Grapheme2Phoneme()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/russian_g2p/Grapheme2Phoneme.py", line 27, in __init__
    'File `{0}` does not exist!'.format(exclusions_dictionary_name)
AssertionError: File `/usr/local/lib/python3.6/site-packages/russian_g2p/data/Phonetic_Exclusions.txt` does not exist!

**Comment by nsu-ai** [comment] 2018-07-02 10:48
Thank you for the feedback! The issue is fixed in "bugfixing" branch, awaiting merge.

**Comment by nsu-ai** [comment] 2018-08-21 09:52
Fixed in [ad0832b](https://github.com/nsu-ai/russian_g2p/commit/ad0832b8eff3d933448e6de0727deba71ac8d10c)

**Closed** 2018-08-21 09:52 UTC
